defmodule AshTest.Repo.Migrations.Indexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:role_mappings, [:user_id, :role],
             name: "role_mappings_unique_entry_index"
           )

    create unique_index(:group_mappings, [:user_id, :group],
             name: "group_mappings_unique_entry_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:group_mappings, [:user_id, :group], name: "group_mappings_unique_entry_index")
    )

    drop_if_exists(
      unique_index(:role_mappings, [:user_id, :role], name: "role_mappings_unique_entry_index")
    )
  end
end
